name: 部署vue-design文档
on:
    push:
        branches:
            - master
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: 检出代码
              uses: actions/checkout@master
            - name: 安装node.js
              uses: actions/setup-node@v1
              with:
                  node-version: "10.x"
            - name: 编译代码
            - run: |
                  npm install
                  npm run docs:build
            - name: 部署文档
              uses: peaceiris/actions-gh-pages@v2.5.0
              env:
                  PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  PUBLISH_BRANCH: gh-pages
                  PUBLISH_DIR: ./docs/.vuepress/dist
